spring.application.name=bookshelf
spring.datasource.url=jdbc:h2:file:${user.home}/.bookshelf/data/bookshelf;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
